---
  api_url:
    description: "URL to the API stream, e.g. 'https://localhost:5665/v1'"
    type: string
    secret: false
    required: true
  api_user:
    description: "API user name to query Icinga2 host for objects"
    type: string
    secret: false
    required: false
  api_password:
    description: "API password for querying Icinga2 for objects"
    type: string
    secret: true
    required: false
  certificate:
    description: "Path to client certificate if using certificate authentication instead of username/password"
    type: string
    secret: false
    required: false
  key:
    description: "Path to client private key if using certificate authentication instead of username/password"
    type: string
    secret: false
    required: false
  ca_file:
    description: "Optional path to CA bundle for validating server-side certificate"
    type: string
    secret: false
    required: false
